"""UserBinaryData model added

Revision ID: 1253d7b49c63
Revises: 4499778c1f63
Create Date: 2025-01-08 02:29:49.598438

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1253d7b49c63"
down_revision = "4499778c1f63"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_binary_data",
        sa.Column("session_id", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("group_id", sa.String(length=50), nullable=True),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("data", sa.LargeBinary(), nullable=False),
        sa.Column("mimetype", sa.String(length=50), nullable=True),
        sa.Column("extension", sa.String(length=10), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_binary_data_direction"),
        "user_binary_data",
        ["direction"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_binary_data_extension"),
        "user_binary_data",
        ["extension"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_binary_data_group_id"),
        "user_binary_data",
        ["group_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_binary_data_id"),
        "user_binary_data",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_binary_data_mimetype"),
        "user_binary_data",
        ["mimetype"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_binary_data_session_id"),
        "user_binary_data",
        ["session_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_binary_data_type"),
        "user_binary_data",
        ["type"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_user_binary_data_type"),
        table_name="user_binary_data",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_binary_data_session_id"),
        table_name="user_binary_data",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_binary_data_mimetype"),
        table_name="user_binary_data",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_binary_data_id"),
        table_name="user_binary_data",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_binary_data_group_id"),
        table_name="user_binary_data",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_binary_data_extension"),
        table_name="user_binary_data",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_binary_data_direction"),
        table_name="user_binary_data",
        schema="public",
    )
    op.drop_table("user_binary_data", schema="public")
    # ### end Alembic commands ###
