"""UserConfig added

Revision ID: 4499778c1f63
Revises:
Create Date: 2024-12-04 12:20:42.815183

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4499778c1f63"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_configs",
        sa.Column("session_id", sa.String(length=50), nullable=False),
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "key", name="_session_key_uc"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_configs_id"),
        "user_configs",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_configs_session_id"),
        "user_configs",
        ["session_id"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_user_configs_session_id"),
        table_name="user_configs",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_configs_id"),
        table_name="user_configs",
        schema="public",
    )
    op.drop_table("user_configs", schema="public")
    # ### end Alembic commands ###
