"""user integrations added

Revision ID: f7e9aa4908e2
Revises: c584958c8871
Create Date: 2025-01-23 12:51:31.154484

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7e9aa4908e2"
down_revision = "c584958c8871"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_integrations",
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("app", sa.String(length=255), nullable=False),
        sa.Column("connection_id", sa.String(length=255), nullable=False),
        sa.Column("meta", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", "app", name="_username_app_uc"),
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_integrations_app"),
        "user_integrations",
        ["app"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_integrations_connection_id"),
        "user_integrations",
        ["connection_id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_integrations_id"),
        "user_integrations",
        ["id"],
        unique=False,
        schema="public",
    )
    op.create_index(
        op.f("ix_public_user_integrations_username"),
        "user_integrations",
        ["username"],
        unique=False,
        schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_public_user_integrations_username"),
        table_name="user_integrations",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_integrations_id"),
        table_name="user_integrations",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_integrations_connection_id"),
        table_name="user_integrations",
        schema="public",
    )
    op.drop_index(
        op.f("ix_public_user_integrations_app"),
        table_name="user_integrations",
        schema="public",
    )
    op.drop_table("user_integrations", schema="public")
    # ### end Alembic commands ###
