# Generated by Django 5.1.3 on 2024-12-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentSessions",
            fields=[
                ("session_id", models.CharField(primary_key=True, serialize=False)),
                ("agent_id", models.CharField(blank=True, null=True)),
                ("user_id", models.CharField(blank=True, null=True)),
                ("memory", models.JSONField(blank=True, null=True)),
                ("agent_data", models.JSONField(blank=True, null=True)),
                ("user_data", models.JSONField(blank=True, null=True)),
                ("session_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.BigIntegerField(blank=True, null=True)),
                ("updated_at", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "agent_sessions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="AlembicVersion",
            fields=[
                (
                    "version_num",
                    models.CharField(max_length=32, primary_key=True, serialize=False),
                ),
            ],
            options={
                "db_table": "alembic_version",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LlmOsDocuments",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, null=True)),
                ("meta_data", models.JSONField(blank=True, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("embedding", models.TextField(blank=True, null=True)),
                ("usage", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, null=True)),
            ],
            options={
                "db_table": "llm_os_documents",
                "managed": False,
            },
        ),
    ]
