# Generated by Django 5.1.3 on 2024-12-02 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "model",
                    models.CharField(
                        choices=[("gpt", "Gpt"), ("llama", "Llama")], max_length=255
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "API Key",
                "verbose_name_plural": "API Keys",
            },
        ),
        migrations.CreateModel(
            name="AgentConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("delegation_directives", models.JSONField(blank=True, null=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[("gpt", "Gpt"), ("llama", "Llama")],
                        default="gpt",
                        max_length=255,
                    ),
                ),
                ("model_id", models.CharField(max_length=255)),
                ("model_config", models.JSONField(default=dict)),
                ("agent_config", models.JSONField(blank=True, default=dict, null=True)),
                ("last_activated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dashboard.apikey",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Config",
                "verbose_name_plural": "Agent Configs",
            },
        ),
    ]
