# Generated by Django 5.1.3 on 2024-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_apikey_agentconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentconfig",
            name="instructions",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
