# Generated by Django 5.1.3 on 2024-12-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_agentconfig_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentconfig",
            name="model_type",
            field=models.CharField(
                choices=[("gpt", "Gpt"), ("llama", "Llama"), ("groq", "Groq")],
                default="gpt",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="model",
            field=models.CharField(
                choices=[("gpt", "Gpt"), ("llama", "Llama"), ("groq", "Groq")],
                max_length=255,
            ),
        ),
    ]
