# Generated by Django 5.1.3 on 2024-12-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_agentconfig_model_type_alter_apikey_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
