# Generated by Django 5.1.3 on 2024-12-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentconfig",
            name="model_type",
            field=models.CharField(
                choices=[("gpt", "GPT"), ("llama", "LLaMA"), ("groq", "Groq")],
                default="gpt",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="model",
            field=models.CharField(
                choices=[("gpt", "GPT"), ("llama", "LLaMA"), ("groq", "Groq")],
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="UserConfig",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meta", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("session_id", models.CharField(db_index=True, max_length=50)),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
            ],
            options={
                "unique_together": {("session_id", "key")},
            },
        ),
    ]
